export const REGISTER_ACCOUNT_REQUEST = 'REGISTER_ACCOUNT_REQUEST';
export const REGISTER_ACCOUNT_SUCCESS = 'REGISTER_ACCOUNT_SUCCESS';
export const REGISTER_ACCOUNT_FAIL = 'REGISTER_ACCOUNT_FAIL';

export const LOGIN_ACCOUNT_REQUEST = 'LOGIN_ACCOUNT_REQUEST';
export const LOGIN_ACCOUNT_SUCCESS = 'LOGIN_ACCOUNT_SUCCESS';
export const LOGIN_ACCOUNT_FAIL = 'LOGIN_ACCOUNT_FAIL';

export const LOGOUT_ACCOUNT_REQUEST = 'LOGOUT_ACCOUNT_REQUEST';
export const LOGOUT_ACCOUNT_SUCCESS = 'LOGOUT_ACCOUNT_SUCCESS';
export const LOGOUT_ACCOUNT_FAIL = 'LOGOUT_ACCOUNT_FAIL';

export const GET_CATEGORIES_ACCOUNT_REQUEST = 'GET_CATEGORIES_ACCOUNT_REQUEST';
export const GET_CATEGORIES_ACCOUNT_SUCCESS = 'GET_CATEGORIES_ACCOUNT_SUCCESS';
export const GET_CATEGORIES_ACCOUNT_FAIL = 'GET_CATEGORIES_ACCOUNT_FAIL';

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';
