export const REGISTER_ACCOUNT_REQUEST = 'REGISTER_ACCOUNT_REQUEST';
export const REGISTER_ACCOUNT_SUCCESS = 'REGISTER_ACCOUNT_SUCCESS';
export const REGISTER_ACCOUNT_FAIL = 'REGISTER_ACCOUNT_FAIL';

export const LOGIN_ACCOUNT_REQUEST = 'LOGIN_ACCOUNT_REQUEST';
export const LOGIN_ACCOUNT_SUCCESS = 'LOGIN_ACCOUNT_SUCCESS';
export const LOGIN_ACCOUNT_FAIL = 'LOGIN_ACCOUNT_FAIL';

export const LOGOUT_ACCOUNT_REQUEST = 'LOGOUT_ACCOUNT_REQUEST';
export const LOGOUT_ACCOUNT_SUCCESS = 'LOGOUT_ACCOUNT_SUCCESS';
export const LOGOUT_ACCOUNT_FAIL = 'LOGOUT_ACCOUNT_FAIL';

export const GET_CATEGORIES_ACCOUNT_REQUEST = 'GET_CATEGORIES_ACCOUNT_REQUEST';
export const GET_CATEGORIES_ACCOUNT_SUCCESS = 'GET_CATEGORIES_ACCOUNT_SUCCESS';
export const GET_CATEGORIES_ACCOUNT_FAIL = 'GET_CATEGORIES_ACCOUNT_FAIL';

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';

export const GET_POST_BY_USER_ID_REQUEST = 'GET_POST_BY_USER_ID_REQUEST';
export const GET_POST_BY_USER_ID_SUCCESS = 'GET_POST_BY_USER_ID_SUCCESS';
export const GET_POST_BY_USER_ID_FAIL = 'GET_POST_BY_USER_ID_FAIL';

export const GET_POST_REQUEST = 'GET_POST_REQUEST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAIL = 'GET_POST_FAIL';

export const ADD_FAVORITE_REQUEST = 'ADD_FAVORITE_REQUEST';
export const ADD_FAVORITE_SUCCESS = 'ADD_FAVORITE_SUCCESS';
export const ADD_FAVORITE_FAIL = 'ADD_FAVORITE_FAIL';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';

export const LOGIN_WITH_SOCIAL_REQUEST = 'LOGIN_WITH_SOCIAL_REQUEST';
export const LOGIN_WITH_SOCIAL_SUCCESS = 'LOGIN_WITH_SOCIAL_SUCCESS';
export const LOGIN_WITH_SOCIAL_FAIL = 'LOGIN_WITH_SOCIAL_FAIL';
